### PR TITLE
Full JLCPcb Assembly merge

### PR DESCRIPTION
**Pull request by prrvchr**
Hi,
I finished integrating the management of BOMs in Eeschema, as well as the change of some components so that the assembly of the cards is reduced to the minimum (only the connectors are assembled by hand, and unfortunately the ATTINY841 which is not available from JLCPcb and LCSC ...)
I changed the footprints of components in KiCad in order to use only those from KiCad 5.1.5.
I made some change on the PCB (move D4 on the modules, and some minor change following the change of footprints ...) to have a clean DRC ...
But it would still be good to check if there is no error ... ;-)
Thank
Pierre
Edit: Maybe it would be good to keep v4.0 for those who want to assemble by hand ... because it may be more difficult with the reduction of footprints (0805 of the modules have been replaced by 0603, etc... )

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Hello, how does the plugin work, does this automatically run from KiCad ?

**Comment by prrvchr** [comment]
Hi Stuart,

> how does the plugin work

I created a repository for the Plugin and I integrated it into diyBMSv4 with [subrepo](https://github.com/ingydotnet/git-subrepo) (it's easy and transparent). the [README.md](https://github.com/prrvchr/KiCad-BOM-CPL-Plugin/blob/master/README.md) file explains its use and I can manage issues if necessary.

> does this automatically run from KiCad

Not really automatically: In KiCad you have to go to Eeschema >> menu Tools >> Generate Bill of Materials. Choose the `bom-cpl-plugin` plugin from the BOM Plugins list (after installing it if necessary) if not already selected. You can adjust the quantity (of controller or module) desired by adding a quantity in the field: Command line.  And then you can generate ...
The fields required for the plugin have already been added to Eeschema

**Comment by kroesche** [comment]
Does this PR have everything needed to order and assembled board from JCLPCB (except for through hole and ATTiny)? This is something I am interested in. We want to use this BMS cell module for a project but need a lot of boards and dont want to hand assemble. Thanks!

**Comment by stuartpittaway** [comment]
Thanks for the pull request, I'm going to decline this one as I've already made many of the changes to the PCB and I also use this

https://dubiouscreations.com/2019/10/21/using-kicad-with-jlcpcb-assembly-service/

to generate the JLC BOM and CPL files for production.
Thanks.

**Pull request closed without merging**
