### PR TITLE
Module V4.50 Parts C440263, C474300 Out of Stock

### PR DESCRIPTION
**Pull request by lowmoode**
D2 Supressor [Datasheet](https://datasheet.lcsc.com/lcsc/1809042032_Littelfuse-SMBJ5-0A_C83333.pdf)
R30 Resistor [Datasheet](https://datasheet.lcsc.com/lcsc/2006112334_YAGEO-RC2010JK-073RL_C606211.pdf)

### CODE REVIEW

**Comment by stuartpittaway** [comment]
Thank you for the pull request.  I doubt that this will be accepted as its a process of "whack a mole" - one day a particular part will be out of stock at JLC, the next day it will be in, so we would end up always chasing part numbers and constantly updating the diagram/GITHUB.

Ideally, it would be great if JLC supported alternative part numbers for the same component, but alas they don't!

**Comment by stienman** [comment]
Could we include a few additional columns in the CSV BOM for alternative
part numbers?  Most of my BOMs include Digikey, DK alt 1, DK alt 2, Mouser,
for instance.  While JLCPCB won't use or accept alternates, as we identify
them it would be nice to track them so when JLCPCB shows the items with low
stock we can look at the BOM and try the other parts.

-Adam

**Comment by stuartpittaway** [comment]
Perhaps they could be added into kicad as new fields.

The trouble starts if I need to change a component value!

**Comment by stienman** [comment]
Component management is a pain, and at some point the result isn't worth
the effort.  If that's here - where we can only list one part number per
component - that's fine. It sounds like you use KiCAD to manage your BOM,
so updating the BOM requires updating the CAD, and that's a lot more effort
than I would want to do every time a new part alternative is identified.  I
stopped using the CAD programs for BOM management years ago due to these
and other inherent limitations.

-Adam

**Comment by stuartpittaway** [comment]
I use GitHub action to automatically generate the BOM, Gerber and pick n place files, which works very well but is tailored to jlcpcb.

We could perhaps have a table/document with cross reference between jlc and other suppliers.

Most people are simply ordering from jlc, but I understand not everyone can or wants to do that. Keeping lots of cross references can cause a lot of work!!

**Pull request closed without merging**
