### PR TITLE
Kicad cleanup, new power dissipation layout

### PR DESCRIPTION
**Pull request by smurfix**
Changes:

    * imported to Kicad v6.0
    * reorganized to use a common component library
    * V440: moved the components to match the editor's 50mil grid (the schematic is not editable otherwise)
    * removed the Gerber ZIP files, they're redundant (so are the Gerbers themselves, but I left those alone for now)
    * connected a couple of misaligned vias and traces
    * moved non-power routes throught the heat dissipation area away
    * added a lot of vias and copper to resistor array, for improved heat dissipation
    * rearranged resistor array for more connections == larger copper area
    * moved the heat protection slit up a bit, for more room in heat dissipation area
    * added "not in schematic" tags to the mount holes

### CODE REVIEW

**Comment by atanisoft** [comment]
@smurfix Can you share a before/after picture of the updated PCB?

**Comment by smurfix** [comment]
@stuartpittaway Umm, not right now, I'll have to mod the controllers and then switch the github action to 6.0. Give me a few days.

@atanisoft you want screenshots, you get screenshots. ;-)
Screenshot from 2022-04-13 17-37-19
Screenshot from 2022-04-13 17-40-11

**Comment by fhorst1** [comment]
Thanks for the effort and cleaning/improving.
Much appreciated!
Now only the component shortage needs to resolve :-)

**Comment by smurfix** [comment]
One additional feature (so to speak) that I'd add is a nice little OSHW logo. ;-)

Next, BTW, will be my take on improving the firmware. ATtiny841 and floating point calculations really aren't a good match; neither are fixed-length packets and quick round trips. Coming soon to a github repository near you.

**Comment by stuartpittaway** [comment]
Couple of points which will need tiding up.

1. @smurfix happy for you to add your name to the back of the PCB, but it shouldn't be attached to the copyright, as that belongs to me.
2. We can't add an OSHW logo to it, as the licence doesn't permit commercial use, so isn't valid for "open source" - even though the design is freely available/open.

**Comment by stuartpittaway** [comment]
Hi.  I've created a KICAD6 branch to keep track of the conversion process.

Note that the controller PCB is currently undergoing a revision in the Feb2022 branch which I'm currently trialling/testing.

**Comment by smurfix** [comment]
No problem, I'll change that.

**Comment by stuartpittaway** [comment]
Has some silkscreen text chopped off the right hand side (near EXTTEMP1) ?

Happy for the revision to jump up to V4.41 as well (although the hardware is identical) it helps with debugging peoples problems.

I think we should also add the GITHUB "hash" to the silkscreen - this is auto generated by the github action processes - see the controller board for an example.

**Comment by smurfix** [comment]
The residue near EXTTEMP1 is from the measurement, which apparently got slightly mispositioned by kicad6. I moved it (and shifted the measurements to the User.Drawings layer as they are misplaced in Silkscreen).

I'll send a PR for an an update shortly.

**Pull request merged**
